require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/customers", type: :request do

  describe "GET /show" do
    it "renders a successful response" do
      customer = create(:customer)
      get customer_url(customer), as: :json
      expect(response).to be_successful
      body = JSON.parse(response.body, symbolize_names: true)
      expect(body).to be_a Hash
      expect(body.keys).to eq([:customer_id, :subscriptions])
      expect(body[:customer_id]).to match(/d+/)
      expect(body[:subscriptions]).to be_an Array
      expect(body[:subscriptions][0]).to be_a Hash
      expect(body[:subscriptions][0].keys).to eq([:title, :price, :status, :frequency])
    end
  end
end
